import { IIRForm } from "../types";

export const NOT_SPECIFIED = "-";

export const COMPLEXIONS = [
  "Fair",
  "Tan",
  "Medium",
  "Dark",
  "Olive",
  "Morena",
  "Moreno",
  "Light",
  "Brown",
  "Deep",
];

export type TabId =
  | "personal"
  | "education"
  | "family"
  | "health"
  | "interests"
  | "testResults"
  | "significantNotes";

export const EMPTY_IIR_FORM: IIRForm = {
  student: {
    basicInfo: {
      firstName: "",
      middleName: {} as any,
      lastName: "",
      email: "",
    },
    personalInfo: {
      id: undefined,
      suffix: "",
      twoByTwoPhotoDataUrl: null,
      studentNumber: "",
      gender: { id: 0 },
      civilStatus: { id: 0 },
      religion: { id: 0 },
      heightM: "",
      weightKg: "",
      complexion: "",
      highSchoolGWA: "",
      program: { id: 0 },
      yearLevel: 1,
      section: "",
      dateOfBirth: "",
      placeOfBirth: "",
      mobileNumber: "",
      telephoneNumber: null,
      isEmployed: false,
      employerName: null,
      employerAddress: null,
      employerContactNumber: null,

      emergencyContact: {
        firstName: "",
        middleName: null,
        lastName: "",
        contactNumber: "",
        relationship: { id: 0 },
        address: {
          region: { id: 0, code: "" },
          province: null,
          city: { id: 0, code: "" },
          barangay: { id: 0, code: "" },
          streetDetail: "",
        },
      },
    } as any,
    addresses: [],
  },
  education: {
    natureOfSchooling: "",
    interruptedDetails: null,
    schools: [],
  },
  family: {
    background: {} as any,
    relatedPersons: [
      {
        firstName: "",
        middleName: null,
        lastName: "",
        dateOfBirth: "",
        educationalAttainment: { id: 0 },
        occupation: null,
        employerName: null,
        employerAddress: null,
        relationship: { id: 1 },
        isParent: true,
        isGuardian: false,
        isLiving: true,
      }, // Father
      {
        firstName: "",
        middleName: null,
        lastName: "",
        dateOfBirth: "",
        educationalAttainment: { id: 0 },
        occupation: null,
        employerName: null,
        employerAddress: null,
        relationship: { id: 2 },
        isParent: true,
        isGuardian: false,
        isLiving: true,
      }, // Mother
      {
        firstName: "",
        middleName: null,
        lastName: "",
        dateOfBirth: "",
        educationalAttainment: { id: 0 },
        occupation: null,
        employerName: null,
        employerAddress: null,
        relationship: { id: 3 },
        isParent: false,
        isGuardian: true,
        isLiving: true,
      }, // Guardian
    ],
    finance: {} as any,
  },
  health: {
    healthRecord: {
      visionHasProblem: false,
      visionDetails: null,
      hearingHasProblem: false,
      hearingDetails: null,
      speechHasProblem: false,
      speechDetails: null,
      generalHealthHasProblem: false,
      generalHealthDetails: null,
      mentalEmotionalHasProblem: false,
      mentalEmotionalDetails: null,
    } as any,
    consultations: [],
  },
  interests: {
    activities: [],
    subjectPreferences: [],
    hobbies: [],
  },
};

export const COMPLETE_IIR_FORM: IIRForm = {
  student: {
    basicInfo: {
      firstName: "John",
      middleName: "Albert",
      lastName: "Doe",
      email: "student@example.com",
    },
    personalInfo: {
      id: undefined,
      suffix: "",
      twoByTwoPhotoDataUrl: null,
      studentNumber: "2022-00001-TG-0",
      gender: { id: 1 },
      civilStatus: { id: 1 },
      religion: { id: 2 },
      heightM: "1.75",
      weightKg: "70",
      complexion: "Tan",
      highSchoolGWA: "90",
      program: { id: 1 },
      yearLevel: 3,
      section: "1",
      dateOfBirth: "2002-01-01",
      placeOfBirth: "Manila",
      mobileNumber: "09123456789",
      telephoneNumber: null,
      isEmployed: false,
      employerName: null,
      employerAddress: null,
      employerContactNumber: null,
      emergencyContact: {
        firstName: "Jane",
        middleName: "",
        lastName: "Doe",
        contactNumber: "09987654321",
        relationship: { id: 2 },
        address: {
          region: { id: 1, code: "1300000000" },
          province: null,
          city: { id: 1, code: "1380601000" },
          barangay: { id: 1, code: "1380601001" },
          streetDetail: "123 Street",
        },
      },
    } as any,
    addresses: [
      {
        addressType: "residential",
        address: {
          region: { id: 1, code: "1300000000" },
          province: null,
          city: { id: 1, code: "1380601000" },
          barangay: { id: 1, code: "1380601001" },
          streetDetail: "123 Street",
        },
      },
      {
        addressType: "provincial",
        address: {
          region: { id: 1, code: "1300000000" },
          province: null,
          city: { id: 1, code: "1380601000" },
          barangay: { id: 1, code: "1380601001" },
          streetDetail: "123 Street",
        },
      },
    ],
  },
  education: {
    natureOfSchooling: "Continuous",
    interruptedDetails: null,
    schools: [
      {
        educationalLevel: { id: 1 },
        schoolName: "Pre-Elem School",
        schoolAddress: "Manila",
        schoolType: "Public",
        yearStarted: "2006",
        yearCompleted: "2008",
        awards: "",
      },
      {
        educationalLevel: { id: 2 },
        schoolName: "Elem School",
        schoolAddress: "Manila",
        schoolType: "Public",
        yearStarted: "2008",
        yearCompleted: "2014",
        awards: "",
      },
      {
        educationalLevel: { id: 3 },
        schoolName: "Junior High School",
        schoolAddress: "Manila",
        schoolType: "Public",
        yearStarted: "2014",
        yearCompleted: "2018",
        awards: "",
      },
      {
        educationalLevel: { id: 4 },
        schoolName: "Senior High School",
        schoolAddress: "Manila",
        schoolType: "Public",
        yearStarted: "2018",
        yearCompleted: "2020",
        awards: "",
      },
    ],
  },
  family: {
    background: {
      parentalStatus: { id: 1 },
      parentalStatusDetails: null,
      brothers: 1,
      sisters: 1,
      employedSiblings: 0,
      ordinalPosition: 1,
      haveQuietPlaceToStudy: true,
      siblingSupportTypes: [],
      isSharingRoom: false,
      roomSharingDetails: null,
      natureOfResidence: { id: 1 },
    } as any,
    relatedPersons: [
      {
        firstName: "Father",
        middleName: null,
        lastName: "Doe",
        dateOfBirth: "1970-01-01",
        educationalAttainment: { id: 4 },
        occupation: "Engineer",
        employerName: "ABC Corp",
        employerAddress: "Manila",
        relationship: { id: 1 },
        isParent: true,
        isGuardian: false,
        isLiving: true,
      },
      {
        firstName: "Mother",
        middleName: null,
        lastName: "Doe",
        dateOfBirth: "1972-01-01",
        educationalAttainment: { id: 4 },
        occupation: "Teacher",
        employerName: "School",
        employerAddress: "Manila",
        relationship: { id: 2 },
        isParent: true,
        isGuardian: false,
        isLiving: true,
      },
    ],
    finance: {
      monthlyFamilyIncomeRange: { id: 5 },
      otherIncomeDetails: null,
      financialSupportTypes: [],
      weeklyAllowance: "500",
    } as any,
  },
  health: {
    healthRecord: {
      visionHasProblem: false,
      visionDetails: null,
      hearingHasProblem: false,
      hearingDetails: null,
      speechHasProblem: false,
      speechDetails: null,
      generalHealthHasProblem: false,
      generalHealthDetails: null,
      mentalEmotionalHasProblem: false,
      mentalEmotionalDetails: null,
    } as any,
    consultations: [],
  },
  interests: {
    activities: [],
    subjectPreferences: [
      { subjectName: "Math", isFavorite: true },
      { subjectName: "Science", isFavorite: true },
      { subjectName: "History", isFavorite: false },
      { subjectName: "English", isFavorite: false },
    ],
    hobbies: [
      { hobbyName: "Reading", priorityRank: 1 },
      { hobbyName: "Gaming", priorityRank: 2 },
    ],
  },
};
